[package]
name = "zk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.11.2"
ark-crypto-primitives = "0.4.0"
ark-groth16 = "0.4.0"
ark-poly = "0.4.0"
ark-relations = "0.5.0"